tool: service_discovery
rules:
  - name: find_http
    regex: "HTTP\\s+(?P<host>\\S+):(?P<port>\\d+)"
    save_to: assets.services.http
  - name: find_mssql
    regex: "MSSQL\\s+(?P<host>\\S+):(?P<port>\\d+)"
    save_to: assets.services.database
